// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type UserStatus string

const (
	UserStatusPENDING   UserStatus = "PENDING"
	UserStatusACTIVE    UserStatus = "ACTIVE"
	UserStatusSUSPENDED UserStatus = "SUSPENDED"
	UserStatusDELETED   UserStatus = "DELETED"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus
	Valid      bool // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type VideoSourceType string

const (
	VideoSourceTypeUPLOAD        VideoSourceType = "UPLOAD"
	VideoSourceTypeSTREAMARCHIVE VideoSourceType = "STREAM_ARCHIVE"
	VideoSourceTypeCLIP          VideoSourceType = "CLIP"
)

func (e *VideoSourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VideoSourceType(s)
	case string:
		*e = VideoSourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for VideoSourceType: %T", src)
	}
	return nil
}

type NullVideoSourceType struct {
	VideoSourceType VideoSourceType
	Valid           bool // Valid is true if VideoSourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVideoSourceType) Scan(value interface{}) error {
	if value == nil {
		ns.VideoSourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VideoSourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVideoSourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VideoSourceType), nil
}

type ChannelStaff struct {
	ChannelID string
	UserID    string
	RoleID    pgtype.Int4
	CreatedAt pgtype.Timestamptz
}

type Follow struct {
	FollowerID  string
	FollowingID string
	CreatedAt   pgtype.Timestamptz
}

type Permission struct {
	ID   int32
	Slug string
}

type Role struct {
	ID   int32
	Name string
}

type RolePermission struct {
	RoleID       int32
	PermissionID int32
}

type Stream struct {
	ID           string
	UserID       pgtype.Text
	Title        string
	CreatedAt    pgtype.Timestamptz
	EndedAt      pgtype.Timestamptz
	PeakViewers  pgtype.Int4
	ThumbnailUrl pgtype.Text
}

type User struct {
	ID           string
	Email        string
	Username     string
	PasswordHash pgtype.Text
	StreamKey    pgtype.Text
	Status       NullUserStatus
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UserProfile struct {
	UserID        string
	DisplayName   string
	Bio           pgtype.Text
	AvatarUrl     pgtype.Text
	FollowerCount pgtype.Int4
	IsLive        pgtype.Bool
	UpdatedAt     pgtype.Timestamptz
}

type UserRole struct {
	UserID string
	RoleID int32
}

type Video struct {
	ID              string
	UserID          string
	StreamID        pgtype.Text
	Title           string
	Url             string
	Description     pgtype.Text
	DurationSeconds int32
	SourceType      VideoSourceType
	CreatedAt       pgtype.Timestamptz
}
